name: Build RustDesk for Windows

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSVC build environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
        override: true
        profile: minimal

    - name: Install build dependencies
      run: |
        choco install -y llvm
        choco install -y nasm
        choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Build with minimal features
      run: |
        # 禁用所有有问题的特性，只构建核心功能
        cargo build --release --target x86_64-pc-windows-msvc --no-default-features --features "flutter" --verbose

    - name: Collect artifacts
      run: |
        mkdir artifacts
        Copy-Item "target\x86_64-pc-windows-msvc\release\rustdesk.exe" -Destination "artifacts\" -ErrorAction SilentlyContinue
        Copy-Item "target\x86_64-pc-windows-msvc\release\*.dll" -Destination "artifacts\" -ErrorAction SilentlyContinue

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rustdesk-windows
        path: artifacts/
        if-no-files-found: warn
